### ISSUE TITLE
ssl issue

### ISSUE THREAD

**Issue by fahedaljghine** [yusefarianpour/the-laravel-fcm-channel#2]
I tried to do as in docs and I got this error

cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html

**Comment by fahedaljghine** [comment]
to solve this issue I had to  add verify =>false to guzzle client in FirebaseChannel Class

`
        $response = $this->client->post(self::API_URI, [
            'headers' => [
                'Authorization' => 'key=' . $this->getApiKey(),
                'Content-Type'  => 'application/json',
            ],
            'body' => $message->formatData(),
            'verify'          => false,
        ]);`

**Comment by fahedaljghine** [comment]
any fix without altering the vendor ?

**Comment by yusefarianpour** [comment]
Dear @fahedaljghine , ssl certificate error fixed.

**Comment by fahedaljghine** [comment]
Thank you Yusef
